### ISSUE TITLE
has_many :through

### ISSUE THREAD

**Issue by hoblin** [goncalossilva/acts_as_paranoid#15]
I have models Client, User and ClientUser with following associations: 
https://gist.github.com/793920

```
ruby-1.8.7-p302 > Client.first.client_users.count
 => 3 
ruby-1.8.7-p302 > Client.first.users.count
 => 3 
ruby-1.8.7-p302 > Client.first.client_users.last.destroy
 => 1 
ruby-1.8.7-p302 > Client.first.client_users.count
 => 2 
ruby-1.8.7-p302 > Client.first.users.count
 => 3 
ruby-1.8.7-p302 > 
```

As you see, deleted_at field not affect on has_many :through association

**Comment by goncalossilva** [comment]
This is a "bug" on Rails itself. I could reproduced it with 3.0.4 but it has been fixed in master.

A related bug report is here: https://rails.lighthouseapp.com/projects/8994/tickets/3610-has_many-through-associations-may-not-respect-default_scope-conditions

A future Rails release will bring a fix for this, so I'll close this issue for now. Thanks for reporting it.
